# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(
                choices=[
                    ('services', 'Услуги мастера'),
                    ('auto', 'Авто и запчасти'),
                    ('food', 'Домашняя выпечка и еда'),
                    ('education', 'Обучение и репетиторы'),
                    ('electronics', 'Электроника'),
                    ('real-estate', 'Недвижимость'),
                    ('jobs', 'Работа'),
                ],
                db_index=True,
                default='services',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
